// react-message-app/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [message, setMessage] = useState('');
  const [displayedMessage, setDisplayedMessage] = useState('Hello World');

  const displayMessage = () => {
    setDisplayedMessage(message);
  };

  return (
    <div style={{ textAlign: 'center' }}>
      <h1>React Message App</h1>
      <input
        type="text"
        placeholder="Message to Display"
        value={message}
        onChange={(e) => setMessage(e.target.value)}
      />
      <button onClick={displayMessage}>Display Message</button>
      <h2>{displayedMessage}</h2>
    </div>
  );
}

export default App;

// angular-message-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  message: string = '';
  displayedMessage: string = 'Hello World';

  displayMessage() {
    this.displayedMessage = this.message;
  }
}

<div style="text-align:center">
  <h1>Angular Message App</h1>
  <input type="text" [(ngModel)]="message" placeholder="Message to Display" />
  <button (click)="displayMessage()">Display Message</button>
  <h2>{{ displayedMessage }}</h2>
</div>
